### ISSUE TITLE
New shinies

### ISSUE THREAD

**Issue by byhlel** [pogotrades/pogotrades.github.io#1]
Hey, not sure how to contribute to the google sheet from wich informations are being fetched,
but a few shinies have been / are going to be released maybe it's time for an update?

According to the webpage last update is 27 october.

**Comment by pogotrades** [comment]
Very busy at the moment but I am aware of this and it's on the to-do list! Hopefully everything should be brought up-to-date within the next couple of weeks when I have some time to spare.
